#!/usr/bin/env bash

set PLATFORM

# try and find a platform file
for pf in "mac" "linux"; do

	if [ -e "${PWD}/.${pf}" ]; then
		PLATFORM=$pf
	fi

done

# check that we have a platform variable
if [ -z "${PLATFORM+x}" ]; then
	echo "You must create either a .mac or .linux file in this folder."
	exit 1
fi

# backup the current ~/.bash_profile
if [ -s "${HOME}/.bash_profile" ]; then
	cp ${HOME}/.bash_profile ${HOME}/.bash_profile_dotfiles_bak
	rm ${HOME}/.bash_profile
	echo "The previous .bash_profile was backed up."
fi

# create a platform file that will be loaded by .bash_profile
echo "${PLATFORM}" > $HOME/.platform
echo ".platform created"

# install the various files
for file in ".bash_profile" ".development" ".bash_aliases" ".bash_colors" ".bash_prompt"; do

	if [ -e ${PWD}/${file} ] && [ ! -h ${HOME}/${file} ]; then
		ln -s ${PWD}/${file} ${HOME}/${file}
		echo "Installed ${file}"
	fi

	# and their platform specific counterparts
	for pf in "mac" "linux"; do

		if [ -e "${PWD}/${file}_${pf}" ] && [ ! -h "${HOME}/${file}_${pf}" ] && [ "${PLATFORM}" = "${pf}" ]; then
			ln -s "${PWD}/${file}_${pf}" "${HOME}/${file}_${pf}"
			echo "Installed ${file}_${pf}"
		fi

	done

done

# setup the gitconfig file which is specific to platform
cp ${PWD}/platform/${PLATFORM}/.gitconfig ${HOME}/.gitconfig
echo "Installed .gitconfig"

# load in the new .bash_profile immediately
source ${HOME}/.bash_profile
echo "Installed the new setup, into this terminal session"
