#!/usr/bin/env bash

# check that we have a platform variable
if [ -z "${PLATFORM}" ]; then
	echo "You must create an environment variable called PLATFORM with either 'mac' or 'linux'"
	exit 1
fi

echo "Uninstalling the dotfiles setup"

# install the various files
for file in ".bash_profile" ".development" ".bash_aliases" ".bash_colors" ".bash_prompt"; do

	if [ -e "${HOME}/${file}" ]; then
		rm "${HOME}/${file}"
		echo "Removed ${file}"
	fi

	# and their platform specific counterparts
	for pf in "mac" "linux"; do

		if [ -e "${HOME}/${file}_${pf}" ]; then
			rm "${HOME}/${file}_${pf}"
			echo "Removed ${file}_${pf}"
		fi

	done

done

echo "Uninstalled, although ${HOME}/.gitconfig has not been removed."
